create table if not exists pokemon(
unique_id int primary key,
pokedex_number int not null,
name text not null,
generation int not null,
status text not null,
species text not null,
type_1 text not null,
type_2 text,
height_m float,
weight_kg float,
ability_1 text,
ability_2 text,
ability_hidden text,
total_points int,
hp int,
attack int,
defense int,
sp_attack int,
sp_defense int,
speed int,
catch_rate int,
base_friendship int,
base_experience int,
growth_rate text,
egg_type_1 text,
egg_type_2 text,
percentage_male float,
percentage_female float,
egg_cycles int,
against_normal float,
against_fire float,
against_water float,
against_electric float,
against_grass float,
against_ice float,
against_fight float,
against_poison float,
against_ground float,
against_flying float,
against_psychic float,
against_bug float,
against_rock float,
against_ghost float,
against_dragon float,
against_dark float,
against_steel float,
against_fairy float
)